# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'flickrTest' do
pod 'Kingfisher', '~> 5.0'
pod 'SnapKit', '~> 5.0.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for flickrTest

end
